name: Build ticket
run-name: Build ticket run-name
on: 
  workflow_dispatch:
    inputs:
      useDifferingTicketTag:
        description: 'Alternative ticket tag if not to use from branch name'     
        required: false
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Pulling the repo to ensure it's up to date
        run: |
          git pull origin ${{ github.ref }}
      - name: Also pulling all the tags
        run: |
          git fetch --tags
      - run: echo "🎉 The job has completed successfully!"
